// Auto-generated from data/urdu-kitab-inventory.json — do not edit manually

export interface CatalogBook {
  id: number;
  name_en: string;
  name_ur: string;
  price: number;
  cost_price: number;
  description_en: string;
  description_ur: string;
  image: string;
  stock: number;
  weight: number;
  is_quran?: boolean;
}

export const PLACEHOLDER_IMAGE = "";

const descEn = (name: string) =>
  `Educational Islamic book from Noorani Makatib: ${name}.`;
const descUr = (name: string) =>
  `نورانی مکاتب کی تعلیمی اسلامی کتاب: ${name}۔`;

export const CATALOG_BOOKS: CatalogBook[] = [
  {
    id: 1,
    name_en: "100 DURUD V SALAM",
    name_ur: "100 DURUD V SALAM",
    price: 15,
    cost_price: 13.6,
    description_en: descEn("100 DURUD V SALAM"),
    description_ur: descUr("100 DURUD V SALAM"),
    image: PLACEHOLDER_IMAGE,
    stock: 334,
    weight: 30,
  },
  {
    id: 2,
    name_en: "Aap Dars E Quran Kese Dein",
    name_ur: "Aap Dars E Quran Kese Dein",
    price: 20,
    cost_price: 15,
    description_en: descEn("Aap Dars E Quran Kese Dein"),
    description_ur: descUr("Aap Dars E Quran Kese Dein"),
    image: PLACEHOLDER_IMAGE,
    stock: 146,
    weight: 70,
  },
  {
    id: 3,
    name_en: "Al Arbaun Madaniyyah",
    name_ur: "Al Arbaun Madaniyyah",
    price: 20,
    cost_price: 0,
    description_en: descEn("Al Arbaun Madaniyyah"),
    description_ur: descUr("Al Arbaun Madaniyyah"),
    image: PLACEHOLDER_IMAGE,
    stock: 106,
    weight: 50,
  },
  {
    id: 4,
    name_en: "Al Arbaun Makkiyyah",
    name_ur: "Al Arbaun Makkiyyah",
    price: 20,
    cost_price: 0,
    description_en: descEn("Al Arbaun Makkiyyah"),
    description_ur: descUr("Al Arbaun Makkiyyah"),
    image: PLACEHOLDER_IMAGE,
    stock: 96,
    weight: 50,
  },
  {
    id: 5,
    name_en: "Bachcho Ka Tohfa-1 Bengali",
    name_ur: "Bachcho Ka Tohfa-1 Bengali",
    price: 25,
    cost_price: 18,
    description_en: descEn("Bachcho Ka Tohfa-1 Bengali"),
    description_ur: descUr("Bachcho Ka Tohfa-1 Bengali"),
    image: PLACEHOLDER_IMAGE,
    stock: 1500,
    weight: 80,
  },
  {
    id: 6,
    name_en: "Bachcho Ka Tohfa-1 English (72 Page)",
    name_ur: "Bachcho Ka Tohfa-1 English (72 Page)",
    price: 40,
    cost_price: 25,
    description_en: descEn("Bachcho Ka Tohfa-1 English (72 Page)"),
    description_ur: descUr("Bachcho Ka Tohfa-1 English (72 Page)"),
    image: PLACEHOLDER_IMAGE,
    stock: 1632,
    weight: 125,
  },
  {
    id: 7,
    name_en: "Bachcho Ka Tohfa-1",
    name_ur: "Bachcho Ka Tohfa-1",
    price: 25,
    cost_price: 13.2,
    description_en: descEn("Bachcho Ka Tohfa-1"),
    description_ur: descUr("Bachcho Ka Tohfa-1"),
    image: PLACEHOLDER_IMAGE,
    stock: 7226,
    weight: 80,
  },
  {
    id: 8,
    name_en: "Bachcho Ka Tohfa-2",
    name_ur: "Bachcho Ka Tohfa-2",
    price: 18,
    cost_price: 10,
    description_en: descEn("Bachcho Ka Tohfa-2"),
    description_ur: descUr("Bachcho Ka Tohfa-2"),
    image: PLACEHOLDER_IMAGE,
    stock: 6551,
    weight: 60,
  },
  {
    id: 9,
    name_en: "Bachcho Ka Tohfa-2 English",
    name_ur: "Bachcho Ka Tohfa-2 English",
    price: 20,
    cost_price: 13,
    description_en: descEn("Bachcho Ka Tohfa-2 English"),
    description_ur: descUr("Bachcho Ka Tohfa-2 English"),
    image: PLACEHOLDER_IMAGE,
    stock: 1,
    weight: 80,
  },
  {
    id: 10,
    name_en: "Bachcho Ko Hifz Kese Karayein",
    name_ur: "Bachcho Ko Hifz Kese Karayein",
    price: 30,
    cost_price: 22,
    description_en: descEn("Bachcho Ko Hifz Kese Karayein"),
    description_ur: descUr("Bachcho Ko Hifz Kese Karayein"),
    image: PLACEHOLDER_IMAGE,
    stock: 151,
    weight: 110,
  },
  {
    id: 11,
    name_en: "Bachcho Ko Padhane Ka Tariqa",
    name_ur: "Bachcho Ko Padhane Ka Tariqa",
    price: 120,
    cost_price: 80,
    description_en: descEn("Bachcho Ko Padhane Ka Tariqa"),
    description_ur: descUr("Bachcho Ko Padhane Ka Tariqa"),
    image: PLACEHOLDER_IMAGE,
    stock: 632,
    weight: 490,
  },
  {
    id: 12,
    name_en: "Bachcho Padhane Ka Tariqa Gujarati",
    name_ur: "Bachcho Padhane Ka Tariqa Gujarati",
    price: 20,
    cost_price: 15,
    description_en: descEn("Bachcho Padhane Ka Tariqa Gujarati"),
    description_ur: descUr("Bachcho Padhane Ka Tariqa Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 25,
    weight: 90,
  },
  {
    id: 13,
    name_en: "Bayanat E Makatib-1",
    name_ur: "Bayanat E Makatib-1",
    price: 170,
    cost_price: 130,
    description_en: descEn("Bayanat E Makatib-1"),
    description_ur: descUr("Bayanat E Makatib-1"),
    image: PLACEHOLDER_IMAGE,
    stock: 728,
    weight: 580,
  },
  {
    id: 14,
    name_en: "Darul Uloom Deoband Aur Maslak E Deoband",
    name_ur: "Darul Uloom Deoband Aur Maslak E Deoband",
    price: 50,
    cost_price: 42,
    description_en: descEn("Darul Uloom Deoband Aur Maslak E Deoband"),
    description_ur: descUr("Darul Uloom Deoband Aur Maslak E Deoband"),
    image: PLACEHOLDER_IMAGE,
    stock: 3,
    weight: 135,
  },
  {
    id: 15,
    name_en: "Dekhi Hui Duniya-1",
    name_ur: "Dekhi Hui Duniya-1",
    price: 90,
    cost_price: 0,
    description_en: descEn("Dekhi Hui Duniya-1"),
    description_ur: descUr("Dekhi Hui Duniya-1"),
    image: PLACEHOLDER_IMAGE,
    stock: 0,
    weight: 310,
  },
  {
    id: 16,
    name_en: "Dekhi Hui Duniya-1 Gujarati",
    name_ur: "Dekhi Hui Duniya-1 Gujarati",
    price: 60,
    cost_price: 0,
    description_en: descEn("Dekhi Hui Duniya-1 Gujarati"),
    description_ur: descUr("Dekhi Hui Duniya-1 Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 0,
    weight: 310,
  },
  {
    id: 17,
    name_en: "Dekhi Hui Duniya-2",
    name_ur: "Dekhi Hui Duniya-2",
    price: 0,
    cost_price: 0,
    description_en: descEn("Dekhi Hui Duniya-2"),
    description_ur: descUr("Dekhi Hui Duniya-2"),
    image: PLACEHOLDER_IMAGE,
    stock: 0,
    weight: 80,
  },
  {
    id: 18,
    name_en: "Dekhi Hui Duniya-2 Gujarati",
    name_ur: "Dekhi Hui Duniya-2 Gujarati",
    price: 35,
    cost_price: 28,
    description_en: descEn("Dekhi Hui Duniya-2 Gujarati"),
    description_ur: descUr("Dekhi Hui Duniya-2 Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 41,
    weight: 180,
  },
  {
    id: 19,
    name_en: "DEKHI HUI DUNIYA-3",
    name_ur: "DEKHI HUI DUNIYA-3",
    price: 90,
    cost_price: 83,
    description_en: descEn("DEKHI HUI DUNIYA-3"),
    description_ur: descUr("DEKHI HUI DUNIYA-3"),
    image: PLACEHOLDER_IMAGE,
    stock: 58,
    weight: 290,
  },
  {
    id: 20,
    name_en: "Dekhi Hui Duniya-3 Gujarati",
    name_ur: "Dekhi Hui Duniya-3 Gujarati",
    price: 100,
    cost_price: 80,
    description_en: descEn("Dekhi Hui Duniya-3 Gujarati"),
    description_ur: descUr("Dekhi Hui Duniya-3 Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 365,
    weight: 430,
  },
  {
    id: 21,
    name_en: "Dekhi Hui Duniya-4",
    name_ur: "Dekhi Hui Duniya-4",
    price: 70,
    cost_price: 58,
    description_en: descEn("Dekhi Hui Duniya-4"),
    description_ur: descUr("Dekhi Hui Duniya-4"),
    image: PLACEHOLDER_IMAGE,
    stock: 42,
    weight: 300,
  },
  {
    id: 22,
    name_en: "Dekhi Hui Duniya-4 Gujarati",
    name_ur: "Dekhi Hui Duniya-4 Gujarati",
    price: 70,
    cost_price: 58,
    description_en: descEn("Dekhi Hui Duniya-4 Gujarati"),
    description_ur: descUr("Dekhi Hui Duniya-4 Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 776,
    weight: 280,
  },
  {
    id: 23,
    name_en: "Dekhi Hui Duniya-5",
    name_ur: "Dekhi Hui Duniya-5",
    price: 70,
    cost_price: 55,
    description_en: descEn("Dekhi Hui Duniya-5"),
    description_ur: descUr("Dekhi Hui Duniya-5"),
    image: PLACEHOLDER_IMAGE,
    stock: 213,
    weight: 280,
  },
  {
    id: 24,
    name_en: "Dekhi Hui Duniya-6",
    name_ur: "Dekhi Hui Duniya-6",
    price: 90,
    cost_price: 60,
    description_en: descEn("Dekhi Hui Duniya-6"),
    description_ur: descUr("Dekhi Hui Duniya-6"),
    image: PLACEHOLDER_IMAGE,
    stock: 469,
    weight: 290,
  },
  {
    id: 25,
    name_en: "Dekhi Hui Duniya-7",
    name_ur: "Dekhi Hui Duniya-7",
    price: 60,
    cost_price: 40,
    description_en: descEn("Dekhi Hui Duniya-7"),
    description_ur: descUr("Dekhi Hui Duniya-7"),
    image: PLACEHOLDER_IMAGE,
    stock: 338,
    weight: 200,
  },
  {
    id: 26,
    name_en: "Dekhi Hui Duniya-7 Gujarati",
    name_ur: "Dekhi Hui Duniya-7 Gujarati",
    price: 100,
    cost_price: 70,
    description_en: descEn("Dekhi Hui Duniya-7 Gujarati"),
    description_ur: descUr("Dekhi Hui Duniya-7 Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 368,
    weight: 180,
  },
  {
    id: 27,
    name_en: "Dekhi Hui Duniya-8",
    name_ur: "Dekhi Hui Duniya-8",
    price: 100,
    cost_price: 60,
    description_en: descEn("Dekhi Hui Duniya-8"),
    description_ur: descUr("Dekhi Hui Duniya-8"),
    image: PLACEHOLDER_IMAGE,
    stock: 833,
    weight: 250,
  },
  {
    id: 28,
    name_en: "Dini Bayanaat-1",
    name_ur: "Dini Bayanaat-1",
    price: 80,
    cost_price: 65,
    description_en: descEn("Dini Bayanaat-1"),
    description_ur: descUr("Dini Bayanaat-1"),
    image: PLACEHOLDER_IMAGE,
    stock: 19,
    weight: 400,
  },
  {
    id: 29,
    name_en: "Dini Bayanaat-2",
    name_ur: "Dini Bayanaat-2",
    price: 80,
    cost_price: 65,
    description_en: descEn("Dini Bayanaat-2"),
    description_ur: descUr("Dini Bayanaat-2"),
    image: PLACEHOLDER_IMAGE,
    stock: 2,
    weight: 440,
  },
  {
    id: 30,
    name_en: "Dini Bayanaat-2 (2)",
    name_ur: "Dini Bayanaat-2 (2)",
    price: 100,
    cost_price: 84,
    description_en: descEn("Dini Bayanaat-2 (2)"),
    description_ur: descUr("Dini Bayanaat-2 (2)"),
    image: PLACEHOLDER_IMAGE,
    stock: 1,
    weight: 440,
  },
  {
    id: 31,
    name_en: "Dini Bayanaat-3",
    name_ur: "Dini Bayanaat-3",
    price: 80,
    cost_price: 65,
    description_en: descEn("Dini Bayanaat-3"),
    description_ur: descUr("Dini Bayanaat-3"),
    image: PLACEHOLDER_IMAGE,
    stock: 11,
    weight: 450,
  },
  {
    id: 32,
    name_en: "Dini Bayanaat-4",
    name_ur: "Dini Bayanaat-4",
    price: 80,
    cost_price: 65,
    description_en: descEn("Dini Bayanaat-4"),
    description_ur: descUr("Dini Bayanaat-4"),
    image: PLACEHOLDER_IMAGE,
    stock: 113,
    weight: 450,
  },
  {
    id: 33,
    name_en: "Dini Bayanaat-5",
    name_ur: "Dini Bayanaat-5",
    price: 80,
    cost_price: 65,
    description_en: descEn("Dini Bayanaat-5"),
    description_ur: descUr("Dini Bayanaat-5"),
    image: PLACEHOLDER_IMAGE,
    stock: 281,
    weight: 370,
  },
  {
    id: 34,
    name_en: "Dini Bayanaat-6",
    name_ur: "Dini Bayanaat-6",
    price: 80,
    cost_price: 65,
    description_en: descEn("Dini Bayanaat-6"),
    description_ur: descUr("Dini Bayanaat-6"),
    image: PLACEHOLDER_IMAGE,
    stock: 52,
    weight: 340,
  },
  {
    id: 35,
    name_en: "Dini Bayanaat-7",
    name_ur: "Dini Bayanaat-7",
    price: 80,
    cost_price: 65,
    description_en: descEn("Dini Bayanaat-7"),
    description_ur: descUr("Dini Bayanaat-7"),
    image: PLACEHOLDER_IMAGE,
    stock: 366,
    weight: 450,
  },
  {
    id: 36,
    name_en: "Dini Bayanaat-8",
    name_ur: "Dini Bayanaat-8",
    price: 80,
    cost_price: 65,
    description_en: descEn("Dini Bayanaat-8"),
    description_ur: descUr("Dini Bayanaat-8"),
    image: PLACEHOLDER_IMAGE,
    stock: 209,
    weight: 420,
  },
  {
    id: 37,
    name_en: "Faiz E Sulemani",
    name_ur: "Faiz E Sulemani",
    price: 100,
    cost_price: 80,
    description_en: descEn("Faiz E Sulemani"),
    description_ur: descUr("Faiz E Sulemani"),
    image: PLACEHOLDER_IMAGE,
    stock: 0,
    weight: 440,
  },
  {
    id: 38,
    name_en: "Faiz E Sulemani Gujarati",
    name_ur: "Faiz E Sulemani Gujarati",
    price: 100,
    cost_price: 80,
    description_en: descEn("Faiz E Sulemani Gujarati"),
    description_ur: descUr("Faiz E Sulemani Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 106,
    weight: 440,
  },
  {
    id: 39,
    name_en: "Gazwaat E Rasul s.a.",
    name_ur: "Gazwaat E Rasul s.a.",
    price: 40,
    cost_price: 0,
    description_en: descEn("Gazwaat E Rasul s.a."),
    description_ur: descUr("Gazwaat E Rasul s.a."),
    image: PLACEHOLDER_IMAGE,
    stock: 115,
    weight: 80,
  },
  {
    id: 40,
    name_en: "Hadis Me Aaye Hue Khawateen Ke Waqiaat-1",
    name_ur: "Hadis Me Aaye Hue Khawateen Ke Waqiaat-1",
    price: 70,
    cost_price: 42,
    description_en: descEn("Hadis Me Aaye Hue Khawateen Ke Waqiaat-1"),
    description_ur: descUr("Hadis Me Aaye Hue Khawateen Ke Waqiaat-1"),
    image: PLACEHOLDER_IMAGE,
    stock: 732,
    weight: 240,
  },
  {
    id: 41,
    name_en: "Hadis Me Aaye Hue Khawateen Ke Waqiaat-1 Gujarati",
    name_ur: "Hadis Me Aaye Hue Khawateen Ke Waqiaat-1 Gujarati",
    price: 70,
    cost_price: 58,
    description_en: descEn("Hadis Me Aaye Hue Khawateen Ke Waqiaat-1 Gujarati"),
    description_ur: descUr("Hadis Me Aaye Hue Khawateen Ke Waqiaat-1 Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 625,
    weight: 230,
  },
  {
    id: 42,
    name_en: "Hadis Me Aaye Hue Khawateen Ke Waqiaat-2",
    name_ur: "Hadis Me Aaye Hue Khawateen Ke Waqiaat-2",
    price: 90,
    cost_price: 70,
    description_en: descEn("Hadis Me Aaye Hue Khawateen Ke Waqiaat-2"),
    description_ur: descUr("Hadis Me Aaye Hue Khawateen Ke Waqiaat-2"),
    image: PLACEHOLDER_IMAGE,
    stock: 504,
    weight: 300,
  },
  {
    id: 43,
    name_en: "Hadis Me Aaye Hue Khawateen Ke Waqiaat-3",
    name_ur: "Hadis Me Aaye Hue Khawateen Ke Waqiaat-3",
    price: 90,
    cost_price: 70,
    description_en: descEn("Hadis Me Aaye Hue Khawateen Ke Waqiaat-3"),
    description_ur: descUr("Hadis Me Aaye Hue Khawateen Ke Waqiaat-3"),
    image: PLACEHOLDER_IMAGE,
    stock: 9,
    weight: 310,
  },
  {
    id: 44,
    name_en: "Hadis Me Aaye Hue Khawateen Ke Waqiaat-4",
    name_ur: "Hadis Me Aaye Hue Khawateen Ke Waqiaat-4",
    price: 80,
    cost_price: 55,
    description_en: descEn("Hadis Me Aaye Hue Khawateen Ke Waqiaat-4"),
    description_ur: descUr("Hadis Me Aaye Hue Khawateen Ke Waqiaat-4"),
    image: PLACEHOLDER_IMAGE,
    stock: 241,
    weight: 260,
  },
  {
    id: 45,
    name_en: "Hadis Me Aaye Hue Khawateen Ke Waqiaat-5",
    name_ur: "Hadis Me Aaye Hue Khawateen Ke Waqiaat-5",
    price: 125,
    cost_price: 80,
    description_en: descEn("Hadis Me Aaye Hue Khawateen Ke Waqiaat-5"),
    description_ur: descUr("Hadis Me Aaye Hue Khawateen Ke Waqiaat-5"),
    image: PLACEHOLDER_IMAGE,
    stock: 756,
    weight: 330,
  },
  {
    id: 46,
    name_en: "Hadis Sharif Padhne Ke Aadab",
    name_ur: "Hadis Sharif Padhne Ke Aadab",
    price: 60,
    cost_price: 40,
    description_en: descEn("Hadis Sharif Padhne Ke Aadab"),
    description_ur: descUr("Hadis Sharif Padhne Ke Aadab"),
    image: PLACEHOLDER_IMAGE,
    stock: 356,
    weight: 150,
  },
  {
    id: 47,
    name_en: "HAZRI REGISTER",
    name_ur: "HAZRI REGISTER",
    price: 100,
    cost_price: 90,
    description_en: descEn("HAZRI REGISTER"),
    description_ur: descUr("HAZRI REGISTER"),
    image: PLACEHOLDER_IMAGE,
    stock: 44,
    weight: 400,
  },
  {
    id: 48,
    name_en: "Huruf E Tahajji Takhti",
    name_ur: "Huruf E Tahajji Takhti",
    price: 10,
    cost_price: 3.8,
    description_en: descEn("Huruf E Tahajji Takhti"),
    description_ur: descUr("Huruf E Tahajji Takhti"),
    image: PLACEHOLDER_IMAGE,
    stock: 3923,
    weight: 10,
  },
  {
    id: 49,
    name_en: "Hz. Mufti Ahmed Sb Khanpuri Db. Ke Awsaaf v Kamaalaat",
    name_ur: "Hz. Mufti Ahmed Sb Khanpuri Db. Ke Awsaaf v Kamaalaat",
    price: 40,
    cost_price: 35,
    description_en: descEn("Hz. Mufti Ahmed Sb Khanpuri Db. Ke Awsaaf v Kamaalaat"),
    description_ur: descUr("Hz. Mufti Ahmed Sb Khanpuri Db. Ke Awsaaf v Kamaalaat"),
    image: PLACEHOLDER_IMAGE,
    stock: 2,
    weight: 100,
  },
  {
    id: 50,
    name_en: "Hz. Mufti Saeed Sb. Rh. Ki Batein Or Yadein",
    name_ur: "Hz. Mufti Saeed Sb. Rh. Ki Batein Or Yadein",
    price: 40,
    cost_price: 30,
    description_en: descEn("Hz. Mufti Saeed Sb. Rh. Ki Batein Or Yadein"),
    description_ur: descUr("Hz. Mufti Saeed Sb. Rh. Ki Batein Or Yadein"),
    image: PLACEHOLDER_IMAGE,
    stock: 372,
    weight: 100,
  },
  {
    id: 51,
    name_en: "Imam Bukhari Rh. Ke Halaat",
    name_ur: "Imam Bukhari Rh. Ke Halaat",
    price: 60,
    cost_price: 45,
    description_en: descEn("Imam Bukhari Rh. Ke Halaat"),
    description_ur: descUr("Imam Bukhari Rh. Ke Halaat"),
    image: PLACEHOLDER_IMAGE,
    stock: 105,
    weight: 150,
  },
  {
    id: 52,
    name_en: "Imam Mehndi Kab Or Kaha Gujarati",
    name_ur: "Imam Mehndi Kab Or Kaha Gujarati",
    price: 60,
    cost_price: 50,
    description_en: descEn("Imam Mehndi Kab Or Kaha Gujarati"),
    description_ur: descUr("Imam Mehndi Kab Or Kaha Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 66,
    weight: 190,
  },
  {
    id: 53,
    name_en: "Islah E Muasharah",
    name_ur: "Islah E Muasharah",
    price: 70,
    cost_price: 50,
    description_en: descEn("Islah E Muasharah"),
    description_ur: descUr("Islah E Muasharah"),
    image: PLACEHOLDER_IMAGE,
    stock: 2,
    weight: 270,
  },
  {
    id: 54,
    name_en: "Islah E Muasharah Gujarati",
    name_ur: "Islah E Muasharah Gujarati",
    price: 90,
    cost_price: 53,
    description_en: descEn("Islah E Muasharah Gujarati"),
    description_ur: descUr("Islah E Muasharah Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 500,
    weight: 290,
  },
  {
    id: 55,
    name_en: "Khutbat E Haram Shareef",
    name_ur: "Khutbat E Haram Shareef",
    price: 130,
    cost_price: 110,
    description_en: descEn("Khutbat E Haram Shareef"),
    description_ur: descUr("Khutbat E Haram Shareef"),
    image: PLACEHOLDER_IMAGE,
    stock: 357,
    weight: 350,
  },
  {
    id: 56,
    name_en: "MAHFUZAT",
    name_ur: "MAHFUZAT",
    price: 35,
    cost_price: 17,
    description_en: descEn("MAHFUZAT"),
    description_ur: descUr("MAHFUZAT"),
    image: PLACEHOLDER_IMAGE,
    stock: 2359,
    weight: 100,
  },
  {
    id: 57,
    name_en: "Mahfuzat Gujarati",
    name_ur: "Mahfuzat Gujarati",
    price: 35,
    cost_price: 25,
    description_en: descEn("Mahfuzat Gujarati"),
    description_ur: descUr("Mahfuzat Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 3127,
    weight: 100,
  },
  {
    id: 58,
    name_en: "Maqamat E Muqaddasa Ka Safar",
    name_ur: "Maqamat E Muqaddasa Ka Safar",
    price: 40,
    cost_price: 0,
    description_en: descEn("Maqamat E Muqaddasa Ka Safar"),
    description_ur: descUr("Maqamat E Muqaddasa Ka Safar"),
    image: PLACEHOLDER_IMAGE,
    stock: 4,
    weight: 120,
  },
  {
    id: 59,
    name_en: "Masnun Wazaif English",
    name_ur: "Masnun Wazaif English",
    price: 20,
    cost_price: 18,
    description_en: descEn("Masnun Wazaif English"),
    description_ur: descUr("Masnun Wazaif English"),
    image: PLACEHOLDER_IMAGE,
    stock: 360,
    weight: 30,
  },
  {
    id: 60,
    name_en: "Masnun Wazaif Gujarati",
    name_ur: "Masnun Wazaif Gujarati",
    price: 25,
    cost_price: 16,
    description_en: descEn("Masnun Wazaif Gujarati"),
    description_ur: descUr("Masnun Wazaif Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 575,
    weight: 50,
  },
  {
    id: 61,
    name_en: "Masnun Wazaif Spanish",
    name_ur: "Masnun Wazaif Spanish",
    price: 25,
    cost_price: 17,
    description_en: descEn("Masnun Wazaif Spanish"),
    description_ur: descUr("Masnun Wazaif Spanish"),
    image: PLACEHOLDER_IMAGE,
    stock: 247,
    weight: 60,
  },
  {
    id: 62,
    name_en: "MASNUN WAZAIF URDU",
    name_ur: "MASNUN WAZAIF URDU",
    price: 25,
    cost_price: 15,
    description_en: descEn("MASNUN WAZAIF URDU"),
    description_ur: descUr("MASNUN WAZAIF URDU"),
    image: PLACEHOLDER_IMAGE,
    stock: 204,
    weight: 50,
  },
  {
    id: 63,
    name_en: "Mujarrabat E Mahmudiyah",
    name_ur: "Mujarrabat E Mahmudiyah",
    price: 50,
    cost_price: 28,
    description_en: descEn("Mujarrabat E Mahmudiyah"),
    description_ur: descUr("Mujarrabat E Mahmudiyah"),
    image: PLACEHOLDER_IMAGE,
    stock: 853,
    weight: 130,
  },
  {
    id: 64,
    name_en: "Mujarrabat E Mahmudiyah Gujarati",
    name_ur: "Mujarrabat E Mahmudiyah Gujarati",
    price: 50,
    cost_price: 30,
    description_en: descEn("Mujarrabat E Mahmudiyah Gujarati"),
    description_ur: descUr("Mujarrabat E Mahmudiyah Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 239,
    weight: 110,
  },
  {
    id: 65,
    name_en: "Mukhtasar Talimuddin Imaani Course Gujarati",
    name_ur: "Mukhtasar Talimuddin Imaani Course Gujarati",
    price: 28,
    cost_price: 18,
    description_en: descEn("Mukhtasar Talimuddin Imaani Course Gujarati"),
    description_ur: descUr("Mukhtasar Talimuddin Imaani Course Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 950,
    weight: 80,
  },
  {
    id: 66,
    name_en: "Namaz Ki Masnun Qirat",
    name_ur: "Namaz Ki Masnun Qirat",
    price: 10,
    cost_price: 5,
    description_en: descEn("Namaz Ki Masnun Qirat"),
    description_ur: descUr("Namaz Ki Masnun Qirat"),
    image: PLACEHOLDER_IMAGE,
    stock: 520,
    weight: 20,
  },
  {
    id: 67,
    name_en: "Nuzul E Isa A.S.",
    name_ur: "Nuzul E Isa A.S.",
    price: 100,
    cost_price: 55,
    description_en: descEn("Nuzul E Isa A.S."),
    description_ur: descUr("Nuzul E Isa A.S."),
    image: PLACEHOLDER_IMAGE,
    stock: 807,
    weight: 250,
  },
  {
    id: 68,
    name_en: "PANJ PARA",
    name_ur: "PANJ PARA",
    price: 110,
    cost_price: 75,
    description_en: descEn("PANJ PARA"),
    description_ur: descUr("PANJ PARA"),
    image: PLACEHOLDER_IMAGE,
    stock: 1418,
    weight: 520,
  },
  {
    id: 69,
    name_en: "PARA E AMM",
    name_ur: "PARA E AMM",
    price: 40,
    cost_price: 22.5,
    description_en: descEn("PARA E AMM"),
    description_ur: descUr("PARA E AMM"),
    image: PLACEHOLDER_IMAGE,
    stock: 5170,
    weight: 130,
  },
  {
    id: 70,
    name_en: "Para E Amm English Edition",
    name_ur: "Para E Amm English Edition",
    price: 40,
    cost_price: 29,
    description_en: descEn("Para E Amm English Edition"),
    description_ur: descUr("Para E Amm English Edition"),
    image: PLACEHOLDER_IMAGE,
    stock: 358,
    weight: 125,
  },
  {
    id: 71,
    name_en: "Qadiyaniyat Ka Taruf",
    name_ur: "Qadiyaniyat Ka Taruf",
    price: 60,
    cost_price: 55,
    description_en: descEn("Qadiyaniyat Ka Taruf"),
    description_ur: descUr("Qadiyaniyat Ka Taruf"),
    image: PLACEHOLDER_IMAGE,
    stock: 59,
    weight: 170,
  },
  {
    id: 72,
    name_en: "Qayamat Ki Nishaniyan",
    name_ur: "Qayamat Ki Nishaniyan",
    price: 150,
    cost_price: 122,
    description_en: descEn("Qayamat Ki Nishaniyan"),
    description_ur: descUr("Qayamat Ki Nishaniyan"),
    image: PLACEHOLDER_IMAGE,
    stock: 773,
    weight: 630,
  },
  {
    id: 73,
    name_en: "Qayamat Ki Nishaniyan Gujarati",
    name_ur: "Qayamat Ki Nishaniyan Gujarati",
    price: 70,
    cost_price: 58,
    description_en: descEn("Qayamat Ki Nishaniyan Gujarati"),
    description_ur: descUr("Qayamat Ki Nishaniyan Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 109,
    weight: 290,
  },
  {
    id: 74,
    name_en: "Quran Majid Me Ambiya E Kiram Ka Taruf",
    name_ur: "Quran Majid Me Ambiya E Kiram Ka Taruf",
    price: 80,
    cost_price: 55,
    description_en: descEn("Quran Majid Me Ambiya E Kiram Ka Taruf"),
    description_ur: descUr("Quran Majid Me Ambiya E Kiram Ka Taruf"),
    image: PLACEHOLDER_IMAGE,
    stock: 238,
    weight: 230,
  },
  {
    id: 75,
    name_en: "Quran Me Aaye Hue Khawateen Ke Waqiaat",
    name_ur: "Quran Me Aaye Hue Khawateen Ke Waqiaat",
    price: 500,
    cost_price: 350,
    description_en: descEn("Quran Me Aaye Hue Khawateen Ke Waqiaat"),
    description_ur: descUr("Quran Me Aaye Hue Khawateen Ke Waqiaat"),
    image: PLACEHOLDER_IMAGE,
    stock: 131,
    weight: 1930,
  },
  {
    id: 76,
    name_en: "Quran Shareef (5-5 Para Pocket Size)",
    name_ur: "Quran Shareef (5-5 Para Pocket Size)",
    price: 200,
    cost_price: 185,
    description_en: descEn("Quran Shareef (5-5 Para Pocket Size)"),
    description_ur: descUr("Quran Shareef (5-5 Para Pocket Size)"),
    image: PLACEHOLDER_IMAGE,
    stock: 584,
    weight: 280,
    is_quran: true,
  },
  {
    id: 77,
    name_en: "QURAN SHAREEF (GUJARATI HIDAYAAT)",
    name_ur: "QURAN SHAREEF (GUJARATI HIDAYAAT)",
    price: 325,
    cost_price: 250,
    description_en: descEn("QURAN SHAREEF (GUJARATI HIDAYAAT)"),
    description_ur: descUr("QURAN SHAREEF (GUJARATI HIDAYAAT)"),
    image: PLACEHOLDER_IMAGE,
    stock: 1284,
    weight: 1010,
    is_quran: true,
  },
  {
    id: 78,
    name_en: "QURAN SHAREEF (URDU HIDAYAAT)",
    name_ur: "QURAN SHAREEF (URDU HIDAYAAT)",
    price: 325,
    cost_price: 250,
    description_en: descEn("QURAN SHAREEF (URDU HIDAYAAT)"),
    description_ur: descUr("QURAN SHAREEF (URDU HIDAYAAT)"),
    image: PLACEHOLDER_IMAGE,
    stock: 1037,
    weight: 1030,
    is_quran: true,
  },
  {
    id: 79,
    name_en: "Qurani Wazaif",
    name_ur: "Qurani Wazaif",
    price: 35,
    cost_price: 21,
    description_en: descEn("Qurani Wazaif"),
    description_ur: descUr("Qurani Wazaif"),
    image: PLACEHOLDER_IMAGE,
    stock: 825,
    weight: 60,
  },
  {
    id: 80,
    name_en: "Qurani Wazaif Gujarati",
    name_ur: "Qurani Wazaif Gujarati",
    price: 30,
    cost_price: 18,
    description_en: descEn("Qurani Wazaif Gujarati"),
    description_ur: descUr("Qurani Wazaif Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 421,
    weight: 60,
  },
  {
    id: 81,
    name_en: "Rauzatul Atfal",
    name_ur: "Rauzatul Atfal",
    price: 25,
    cost_price: 11.5,
    description_en: descEn("Rauzatul Atfal"),
    description_ur: descUr("Rauzatul Atfal"),
    image: PLACEHOLDER_IMAGE,
    stock: 842,
    weight: 80,
  },
  {
    id: 82,
    name_en: "Rauzatul Atfal English (64 Page)",
    name_ur: "Rauzatul Atfal English (64 Page)",
    price: 40,
    cost_price: 23,
    description_en: descEn("Rauzatul Atfal English (64 Page)"),
    description_ur: descUr("Rauzatul Atfal English (64 Page)"),
    image: PLACEHOLDER_IMAGE,
    stock: 476,
    weight: 105,
  },
  {
    id: 83,
    name_en: "Rehbar E Muawin",
    name_ur: "Rehbar E Muawin",
    price: 30,
    cost_price: 20,
    description_en: descEn("Rehbar E Muawin"),
    description_ur: descUr("Rehbar E Muawin"),
    image: PLACEHOLDER_IMAGE,
    stock: 572,
    weight: 100,
  },
  {
    id: 84,
    name_en: "Saraya Rasul s.a.",
    name_ur: "Saraya Rasul s.a.",
    price: 70,
    cost_price: 0,
    description_en: descEn("Saraya Rasul s.a."),
    description_ur: descUr("Saraya Rasul s.a."),
    image: PLACEHOLDER_IMAGE,
    stock: 9,
    weight: 160,
  },
  {
    id: 85,
    name_en: "Seh Parah English Edition",
    name_ur: "Seh Parah English Edition",
    price: 70,
    cost_price: 53,
    description_en: descEn("Seh Parah English Edition"),
    description_ur: descUr("Seh Parah English Edition"),
    image: PLACEHOLDER_IMAGE,
    stock: 190,
    weight: 210,
  },
  {
    id: 86,
    name_en: "Shadi Ki Pehli Raat",
    name_ur: "Shadi Ki Pehli Raat",
    price: 80,
    cost_price: 60,
    description_en: descEn("Shadi Ki Pehli Raat"),
    description_ur: descUr("Shadi Ki Pehli Raat"),
    image: PLACEHOLDER_IMAGE,
    stock: 801,
    weight: 230,
  },
  {
    id: 87,
    name_en: "Shadi Ki Pehli Raat Gujarati",
    name_ur: "Shadi Ki Pehli Raat Gujarati",
    price: 40,
    cost_price: 28,
    description_en: descEn("Shadi Ki Pehli Raat Gujarati"),
    description_ur: descUr("Shadi Ki Pehli Raat Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 732,
    weight: 110,
  },
  {
    id: 88,
    name_en: "Tadribi Kapi",
    name_ur: "Tadribi Kapi",
    price: 30,
    cost_price: 25,
    description_en: descEn("Tadribi Kapi"),
    description_ur: descUr("Tadribi Kapi"),
    image: PLACEHOLDER_IMAGE,
    stock: 282,
    weight: 120,
  },
  {
    id: 89,
    name_en: "Tadribi Kapi Pocket Size",
    name_ur: "Tadribi Kapi Pocket Size",
    price: 15,
    cost_price: 9,
    description_en: descEn("Tadribi Kapi Pocket Size"),
    description_ur: descUr("Tadribi Kapi Pocket Size"),
    image: PLACEHOLDER_IMAGE,
    stock: 389,
    weight: 30,
  },
  {
    id: 90,
    name_en: "Talimuddin-1",
    name_ur: "Talimuddin-1",
    price: 35,
    cost_price: 16,
    description_en: descEn("Talimuddin-1"),
    description_ur: descUr("Talimuddin-1"),
    image: PLACEHOLDER_IMAGE,
    stock: 3898,
    weight: 100,
  },
  {
    id: 91,
    name_en: "Talimuddin-1 Gujarati",
    name_ur: "Talimuddin-1 Gujarati",
    price: 35,
    cost_price: 25,
    description_en: descEn("Talimuddin-1 Gujarati"),
    description_ur: descUr("Talimuddin-1 Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 796,
    weight: 100,
  },
  {
    id: 92,
    name_en: "Talimuddin-2",
    name_ur: "Talimuddin-2",
    price: 45,
    cost_price: 27,
    description_en: descEn("Talimuddin-2"),
    description_ur: descUr("Talimuddin-2"),
    image: PLACEHOLDER_IMAGE,
    stock: 52,
    weight: 120,
  },
  {
    id: 93,
    name_en: "Talimuddin-3",
    name_ur: "Talimuddin-3",
    price: 50,
    cost_price: 28,
    description_en: descEn("Talimuddin-3"),
    description_ur: descUr("Talimuddin-3"),
    image: PLACEHOLDER_IMAGE,
    stock: 1777,
    weight: 140,
  },
  {
    id: 94,
    name_en: "Talimuddin-4",
    name_ur: "Talimuddin-4",
    price: 55,
    cost_price: 35.8,
    description_en: descEn("Talimuddin-4"),
    description_ur: descUr("Talimuddin-4"),
    image: PLACEHOLDER_IMAGE,
    stock: 2168,
    weight: 190,
  },
  {
    id: 95,
    name_en: "Talimuddin-5",
    name_ur: "Talimuddin-5",
    price: 55,
    cost_price: 35,
    description_en: descEn("Talimuddin-5"),
    description_ur: descUr("Talimuddin-5"),
    image: PLACEHOLDER_IMAGE,
    stock: 338,
    weight: 160,
  },
  {
    id: 96,
    name_en: "Talimuddin-6",
    name_ur: "Talimuddin-6",
    price: 90,
    cost_price: 50,
    description_en: descEn("Talimuddin-6"),
    description_ur: descUr("Talimuddin-6"),
    image: PLACEHOLDER_IMAGE,
    stock: 120,
    weight: 260,
  },
  {
    id: 97,
    name_en: "Talimuddin-7",
    name_ur: "Talimuddin-7",
    price: 110,
    cost_price: 63,
    description_en: descEn("Talimuddin-7"),
    description_ur: descUr("Talimuddin-7"),
    image: PLACEHOLDER_IMAGE,
    stock: 1839,
    weight: 330,
  },
  {
    id: 98,
    name_en: "Taqabul E Adiyaan",
    name_ur: "Taqabul E Adiyaan",
    price: 40,
    cost_price: 35,
    description_en: descEn("Taqabul E Adiyaan"),
    description_ur: descUr("Taqabul E Adiyaan"),
    image: PLACEHOLDER_IMAGE,
    stock: 78,
    weight: 100,
  },
  {
    id: 99,
    name_en: "Taysirul Quran",
    name_ur: "Taysirul Quran",
    price: 750,
    cost_price: 620,
    description_en: descEn("Taysirul Quran"),
    description_ur: descUr("Taysirul Quran"),
    image: PLACEHOLDER_IMAGE,
    stock: 240,
    weight: 2900,
  },
  {
    id: 100,
    name_en: "Taysirul Quran Gujarati",
    name_ur: "Taysirul Quran Gujarati",
    price: 650,
    cost_price: 540,
    description_en: descEn("Taysirul Quran Gujarati"),
    description_ur: descUr("Taysirul Quran Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 494,
    weight: 2560,
  },
  {
    id: 101,
    name_en: "The Emergence Of The Mahdi",
    name_ur: "The Emergence Of The Mahdi",
    price: 130,
    cost_price: 108,
    description_en: descEn("The Emergence Of The Mahdi"),
    description_ur: descUr("The Emergence Of The Mahdi"),
    image: PLACEHOLDER_IMAGE,
    stock: 4,
    weight: 260,
  },
  {
    id: 102,
    name_en: "URDU QAYDA",
    name_ur: "URDU QAYDA",
    price: 28,
    cost_price: 11.5,
    description_en: descEn("URDU QAYDA"),
    description_ur: descUr("URDU QAYDA"),
    image: PLACEHOLDER_IMAGE,
    stock: 10423,
    weight: 80,
  },
  {
    id: 103,
    name_en: "Zuhure Mehdi",
    name_ur: "Zuhure Mehdi",
    price: 120,
    cost_price: 97,
    description_en: descEn("Zuhure Mehdi"),
    description_ur: descUr("Zuhure Mehdi"),
    image: PLACEHOLDER_IMAGE,
    stock: 951,
    weight: 550,
  },
  {
    id: 104,
    name_en: "Zuhure Mehdi Arbi",
    name_ur: "Zuhure Mehdi Arbi",
    price: 200,
    cost_price: 180,
    description_en: descEn("Zuhure Mehdi Arbi"),
    description_ur: descUr("Zuhure Mehdi Arbi"),
    image: PLACEHOLDER_IMAGE,
    stock: 18,
    weight: 260,
  },
  {
    id: 105,
    name_en: "Ramzan Ke Ruhani Aamal Urdu",
    name_ur: "Ramzan Ke Ruhani Aamal Urdu",
    price: 50,
    cost_price: 0,
    description_en: descEn("Ramzan Ke Ruhani Aamal Urdu"),
    description_ur: descUr("Ramzan Ke Ruhani Aamal Urdu"),
    image: PLACEHOLDER_IMAGE,
    stock: 22,
    weight: 200,
  },
  {
    id: 106,
    name_en: "Ramzan Ke Ruhani Aamal Gujarati",
    name_ur: "Ramzan Ke Ruhani Aamal Gujarati",
    price: 50,
    cost_price: 0,
    description_en: descEn("Ramzan Ke Ruhani Aamal Gujarati"),
    description_ur: descUr("Ramzan Ke Ruhani Aamal Gujarati"),
    image: PLACEHOLDER_IMAGE,
    stock: 10,
    weight: 190,
  },
  {
    id: 107,
    name_en: "Ishq E Rasul s.a. Ke Waqiaat",
    name_ur: "Ishq E Rasul s.a. Ke Waqiaat",
    price: 50,
    cost_price: 0,
    description_en: descEn("Ishq E Rasul s.a. Ke Waqiaat"),
    description_ur: descUr("Ishq E Rasul s.a. Ke Waqiaat"),
    image: PLACEHOLDER_IMAGE,
    stock: 22,
    weight: 120,
  },
];

export const DEFAULT_BOOKS = CATALOG_BOOKS;
