-- Seed catalog from PRICE LIST.xlsx (replaces existing books)
-- WARNING: truncates orders — run only on fresh/reset DB
TRUNCATE order_items, orders RESTART IDENTITY CASCADE;
TRUNCATE books RESTART IDENTITY CASCADE;

INSERT INTO books (name_en, name_ur, price, description_en, description_ur, image, stock, weight) VALUES
('Quran Sharif', 'Quran Sharif', 325, 'Educational Islamic book from Noorani Makatib: Quran Sharif.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Quran Sharif۔', '', 50, 80),
('Dekhi Hui Duniya 1', 'Dekhi Hui Duniya 1', 333, 'Educational Islamic book from Noorani Makatib: Dekhi Hui Duniya 1.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Dekhi Hui Duniya 1۔', '', 50, 80),
('Dekhi Hui Duniya 2', 'Dekhi Hui Duniya 2', 333, 'Educational Islamic book from Noorani Makatib: Dekhi Hui Duniya 2.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Dekhi Hui Duniya 2۔', '', 50, 80),
('Dekhi Hui Duniya 3', 'Dekhi Hui Duniya 3', 90, 'Educational Islamic book from Noorani Makatib: Dekhi Hui Duniya 3.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Dekhi Hui Duniya 3۔', '', 50, 80),
('Dekhi Hui Duniya 4', 'Dekhi Hui Duniya 4', 70, 'Educational Islamic book from Noorani Makatib: Dekhi Hui Duniya 4.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Dekhi Hui Duniya 4۔', '', 50, 80),
('Dekhi Hui Duniya 5', 'Dekhi Hui Duniya 5', 70, 'Educational Islamic book from Noorani Makatib: Dekhi Hui Duniya 5.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Dekhi Hui Duniya 5۔', '', 50, 80),
('Dekhi Hui Duniya 6', 'Dekhi Hui Duniya 6', 90, 'Educational Islamic book from Noorani Makatib: Dekhi Hui Duniya 6.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Dekhi Hui Duniya 6۔', '', 50, 80),
('Dekhi Hui Duniya 7', 'Dekhi Hui Duniya 7', 60, 'Educational Islamic book from Noorani Makatib: Dekhi Hui Duniya 7.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Dekhi Hui Duniya 7۔', '', 50, 80),
('Dekhi Hui Duniya 7 (2)', 'Dekhi Hui Duniya 7 (2)', 60, 'Educational Islamic book from Noorani Makatib: Dekhi Hui Duniya 7 (2).', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Dekhi Hui Duniya 7 (2)۔', '', 50, 80),
('Dekhi Hui Duniya 8', 'Dekhi Hui Duniya 8', 100, 'Educational Islamic book from Noorani Makatib: Dekhi Hui Duniya 8.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Dekhi Hui Duniya 8۔', '', 50, 80),
('Qurani Khawatin', 'Qurani Khawatin', 500, 'Educational Islamic book from Noorani Makatib: Qurani Khawatin.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Qurani Khawatin۔', '', 50, 80),
('Hadisi Khawatin-1', 'Hadisi Khawatin-1', 70, 'Educational Islamic book from Noorani Makatib: Hadisi Khawatin-1.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Hadisi Khawatin-1۔', '', 50, 80),
('Hadisi Khawatin-2', 'Hadisi Khawatin-2', 90, 'Educational Islamic book from Noorani Makatib: Hadisi Khawatin-2.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Hadisi Khawatin-2۔', '', 50, 80),
('Hadisi Khawatin-3', 'Hadisi Khawatin-3', 90, 'Educational Islamic book from Noorani Makatib: Hadisi Khawatin-3.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Hadisi Khawatin-3۔', '', 50, 80),
('Hadisi Khawatin-4', 'Hadisi Khawatin-4', 80, 'Educational Islamic book from Noorani Makatib: Hadisi Khawatin-4.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Hadisi Khawatin-4۔', '', 50, 80),
('Hadisi Khawatin-5', 'Hadisi Khawatin-5', 125, 'Educational Islamic book from Noorani Makatib: Hadisi Khawatin-5.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Hadisi Khawatin-5۔', '', 50, 80),
('Shadi Ki Raat', 'Shadi Ki Raat', 80, 'Educational Islamic book from Noorani Makatib: Shadi Ki Raat.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Shadi Ki Raat۔', '', 50, 80),
('Zuhure Mehdi', 'Zuhure Mehdi', 120, 'Educational Islamic book from Noorani Makatib: Zuhure Mehdi.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Zuhure Mehdi۔', '', 50, 80),
('Islahe Muashara', 'Islahe Muashara', 70, 'Educational Islamic book from Noorani Makatib: Islahe Muashara.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Islahe Muashara۔', '', 50, 80),
('Masnoon Wazaif New', 'Masnoon Wazaif New', 25, 'Educational Islamic book from Noorani Makatib: Masnoon Wazaif New.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Masnoon Wazaif New۔', '', 50, 80),
('Talemuddin-1', 'Talemuddin-1', 35, 'Educational Islamic book from Noorani Makatib: Talemuddin-1.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Talemuddin-1۔', '', 50, 80),
('Talemuddin-2', 'Talemuddin-2', 45, 'Educational Islamic book from Noorani Makatib: Talemuddin-2.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Talemuddin-2۔', '', 50, 80),
('Talemuddin-3', 'Talemuddin-3', 50, 'Educational Islamic book from Noorani Makatib: Talemuddin-3.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Talemuddin-3۔', '', 50, 80),
('Talemuddin-4', 'Talemuddin-4', 55, 'Educational Islamic book from Noorani Makatib: Talemuddin-4.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Talemuddin-4۔', '', 50, 80),
('Talemuddin-5', 'Talemuddin-5', 55, 'Educational Islamic book from Noorani Makatib: Talemuddin-5.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Talemuddin-5۔', '', 50, 80),
('Talemuddin-6', 'Talemuddin-6', 90, 'Educational Islamic book from Noorani Makatib: Talemuddin-6.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Talemuddin-6۔', '', 50, 80),
('Talemuddin-7', 'Talemuddin-7', 110, 'Educational Islamic book from Noorani Makatib: Talemuddin-7.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Talemuddin-7۔', '', 50, 80),
('Talemuddin-7 (2)', 'Talemuddin-7 (2)', 110, 'Educational Islamic book from Noorani Makatib: Talemuddin-7 (2).', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Talemuddin-7 (2)۔', '', 50, 80),
('Baccho Ka Tohfa-1', 'Baccho Ka Tohfa-1', 25, 'Educational Islamic book from Noorani Makatib: Baccho Ka Tohfa-1.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Baccho Ka Tohfa-1۔', '', 50, 80),
('Baccho Ka Tohfa-2', 'Baccho Ka Tohfa-2', 18, 'Educational Islamic book from Noorani Makatib: Baccho Ka Tohfa-2.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Baccho Ka Tohfa-2۔', '', 50, 80),
('Rauzatulatfal', 'Rauzatulatfal', 25, 'Educational Islamic book from Noorani Makatib: Rauzatulatfal.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Rauzatulatfal۔', '', 50, 80),
('Rauzatulatfal (2)', 'Rauzatulatfal (2)', 25, 'Educational Islamic book from Noorani Makatib: Rauzatulatfal (2).', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Rauzatulatfal (2)۔', '', 50, 80),
('Aadabe Hadees', 'Aadabe Hadees', 60, 'Educational Islamic book from Noorani Makatib: Aadabe Hadees.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Aadabe Hadees۔', '', 50, 80),
('Taiserul Quran Set', 'Taiserul Quran Set', 750, 'Educational Islamic book from Noorani Makatib: Taiserul Quran Set.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Taiserul Quran Set۔', '', 50, 80),
('Taiserul Quran-1', 'Taiserul Quran-1', 333, 'Educational Islamic book from Noorani Makatib: Taiserul Quran-1.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Taiserul Quran-1۔', '', 50, 80),
('Taiserul Quran-2', 'Taiserul Quran-2', 333, 'Educational Islamic book from Noorani Makatib: Taiserul Quran-2.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Taiserul Quran-2۔', '', 50, 80),
('Taiserul Quran-3', 'Taiserul Quran-3', 333, 'Educational Islamic book from Noorani Makatib: Taiserul Quran-3.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Taiserul Quran-3۔', '', 50, 80),
('Maslake Deoband', 'Maslake Deoband', 50, 'Educational Islamic book from Noorani Makatib: Maslake Deoband.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Maslake Deoband۔', '', 50, 80),
('Mahfuzat', 'Mahfuzat', 35, 'Educational Islamic book from Noorani Makatib: Mahfuzat.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Mahfuzat۔', '', 50, 80),
('Par E Aam', 'Par E Aam', 40, 'Educational Islamic book from Noorani Makatib: Par E Aam.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Par E Aam۔', '', 50, 80),
('Panj  Para', 'Panj  Para', 110, 'Educational Islamic book from Noorani Makatib: Panj  Para.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Panj  Para۔', '', 50, 80),
('Urdu Ka Kaida', 'Urdu Ka Kaida', 28, 'Educational Islamic book from Noorani Makatib: Urdu Ka Kaida.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Urdu Ka Kaida۔', '', 50, 80),
('Urdu Ka Kaida (2)', 'Urdu Ka Kaida (2)', 28, 'Educational Islamic book from Noorani Makatib: Urdu Ka Kaida (2).', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Urdu Ka Kaida (2)۔', '', 50, 80),
('Rehbare Muawin', 'Rehbare Muawin', 30, 'Educational Islamic book from Noorani Makatib: Rehbare Muawin.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Rehbare Muawin۔', '', 50, 80),
('Baccho Ko Parhane Ka Tarika', 'Baccho Ko Parhane Ka Tarika', 120, 'Educational Islamic book from Noorani Makatib: Baccho Ko Parhane Ka Tarika.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Baccho Ko Parhane Ka Tarika۔', '', 50, 80),
('Darse Quran Kese De', 'Darse Quran Kese De', 20, 'Educational Islamic book from Noorani Makatib: Darse Quran Kese De.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Darse Quran Kese De۔', '', 50, 80),
('Baccho Ko Hifz Kese Karaye', 'Baccho Ko Hifz Kese Karaye', 30, 'Educational Islamic book from Noorani Makatib: Baccho Ko Hifz Kese Karaye.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Baccho Ko Hifz Kese Karaye۔', '', 50, 80),
('Imam Bukhari Rh', 'Imam Bukhari Rh', 60, 'Educational Islamic book from Noorani Makatib: Imam Bukhari Rh.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Imam Bukhari Rh۔', '', 50, 80),
('Mufti Saeed Sb Rh', 'Mufti Saeed Sb Rh', 40, 'Educational Islamic book from Noorani Makatib: Mufti Saeed Sb Rh.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Mufti Saeed Sb Rh۔', '', 50, 80),
('Faize Sulemani', 'Faize Sulemani', 333, 'Educational Islamic book from Noorani Makatib: Faize Sulemani.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Faize Sulemani۔', '', 50, 80),
('Takabule Adiyan', 'Takabule Adiyan', 40, 'Educational Islamic book from Noorani Makatib: Takabule Adiyan.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Takabule Adiyan۔', '', 50, 80),
('Kadiyaniyat Ka Taruf', 'Kadiyaniyat Ka Taruf', 60, 'Educational Islamic book from Noorani Makatib: Kadiyaniyat Ka Taruf.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Kadiyaniyat Ka Taruf۔', '', 50, 80),
('Muzarabate Mahmood', 'Muzarabate Mahmood', 50, 'Educational Islamic book from Noorani Makatib: Muzarabate Mahmood.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Muzarabate Mahmood۔', '', 50, 80),
('Qurani Wazaif', 'Qurani Wazaif', 35, 'Educational Islamic book from Noorani Makatib: Qurani Wazaif.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Qurani Wazaif۔', '', 50, 80),
('Ambiya E Kiram', 'Ambiya E Kiram', 80, 'Educational Islamic book from Noorani Makatib: Ambiya E Kiram.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Ambiya E Kiram۔', '', 50, 80),
('Tadribi Kapi Big', 'Tadribi Kapi Big', 30, 'Educational Islamic book from Noorani Makatib: Tadribi Kapi Big.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Tadribi Kapi Big۔', '', 50, 80),
('Tadribi Kapi Small', 'Tadribi Kapi Small', 15, 'Educational Islamic book from Noorani Makatib: Tadribi Kapi Small.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Tadribi Kapi Small۔', '', 50, 80),
('Nuzule Isa', 'Nuzule Isa', 100, 'Educational Islamic book from Noorani Makatib: Nuzule Isa.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Nuzule Isa۔', '', 50, 80),
('Khutbate Haram', 'Khutbate Haram', 130, 'Educational Islamic book from Noorani Makatib: Khutbate Haram.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Khutbate Haram۔', '', 50, 80),
('100 Durud', '100 Durud', 15, 'Educational Islamic book from Noorani Makatib: 100 Durud.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: 100 Durud۔', '', 50, 80),
('N.M.Taaruf Colour', 'N.M.Taaruf Colour', 150, 'Educational Islamic book from Noorani Makatib: N.M.Taaruf Colour.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: N.M.Taaruf Colour۔', '', 50, 80),
('N.M.Taaruf Sadi', 'N.M.Taaruf Sadi', 70, 'Educational Islamic book from Noorani Makatib: N.M.Taaruf Sadi.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: N.M.Taaruf Sadi۔', '', 50, 80),
('Bayanat E Makatib', 'Bayanat E Makatib', 170, 'Educational Islamic book from Noorani Makatib: Bayanat E Makatib.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Bayanat E Makatib۔', '', 50, 80),
('Pocket Size Quran', 'Pocket Size Quran', 200, 'Educational Islamic book from Noorani Makatib: Pocket Size Quran.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Pocket Size Quran۔', '', 50, 80),
('Takhti', 'Takhti', 10, 'Educational Islamic book from Noorani Makatib: Takhti.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Takhti۔', '', 50, 80),
('Kayamat', 'Kayamat', 150, 'Educational Islamic book from Noorani Makatib: Kayamat.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Kayamat۔', '', 50, 80),
('Masnoon Qirat', 'Masnoon Qirat', 333, 'Educational Islamic book from Noorani Makatib: Masnoon Qirat.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Masnoon Qirat۔', '', 50, 80),
('Mufti Ahmed Sb', 'Mufti Ahmed Sb', 40, 'Educational Islamic book from Noorani Makatib: Mufti Ahmed Sb.', 'نورانی مکاتب کی تعلیمی اسلامی کتاب: Mufti Ahmed Sb۔', '', 50, 80);